name: 部署产业数据中心

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 构建项目
      run: npm run build
      
    - name: 复制预览页面
      run: |
        cp preview.html dist/
        echo "预览页面已复制到dist目录"
        
    - name: 部署到GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        
    - name: 输出部署信息
      run: |
        echo "🚀 部署完成！"
        echo "主站地址: https://kehan857.github.io/Industrial-Data-Center110/"
        echo "预览地址: https://kehan857.github.io/Industrial-Data-Center110/preview.html" 