name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build with Docker
      run: |
        echo "Building with Docker..."
        docker run --rm -v $(pwd):/app -w /app node:18-alpine sh -c "
          echo 'Node.js version:'
          node --version
          echo 'npm version:'
          npm --version
          echo 'Current directory:'
          pwd
          echo 'Files in current directory:'
          ls -la
          echo 'Installing dependencies...'
          npm install --no-optional --no-audit --no-fund
          echo 'Building project...'
          npm run build
        "
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
