name: Simple Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: List directory contents
      run: |
        echo "=== 当前目录内容 ==="
        pwd
        ls -la
        
    - name: Check for package.json
      run: |
        echo "=== 检查package.json ==="
        if [ -f "Desktop/国华知识库/package.json" ]; then
          echo "找到package.json文件"
          cat "Desktop/国华知识库/package.json" | head -10
        else
          echo "未找到package.json文件"
          find . -name "package.json" -type f
        fi
        
    - name: Install Node.js
      run: |
        echo "=== 安装Node.js ==="
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node --version
        npm --version
        
    - name: Install dependencies
      run: |
        echo "=== 安装依赖 ==="
        cd "Desktop/国华知识库"
        npm install --no-optional --no-audit --no-fund
        
    - name: Build project
      run: |
        echo "=== 构建项目 ==="
        cd "Desktop/国华知识库"
        npm run build
        
    - name: Check build output
      run: |
        echo "=== 检查构建输出 ==="
        cd "Desktop/国华知识库"
        ls -la dist/ || echo "dist目录不存在"
